name: spatialite # you probably want to 'snapcraft register <name>'
version: '5.0.1'
summary: 'spatialite-tools is a collection of CLI tools supporting SpatiaLite'
description: |
  spatialite-tools is a collection of open source Command Line Interface (CLI) tools supporting SpatiaLite.

    - spatialite: a complete CLI front-end, more or less equivalent to the well known sqlite3 front-end, but fully supporting SpatiaLite
    - spatialite_tool: a tool supporting import/export of Shapefiles and DBF-files
    - shp_doctor: a diagnostic tool to check anomalous shapefiles
    - exif_loader: an import tool for EXIF or EXIF-GPS (JPEG) pictures
    - spatialite_network: a tool creating a VirtualNetwork (supporting shortest path / routing SQL queries)
    - spatialite_gml: a tool importing GML files
    - spatialite_convert: a tool converting DB-files from different versions of SpatiaLite
    - spatialite_dxf: an tool importing DXF files
    - OSM-tools: spatialite_osm_raw, spatialite_osm_filter, spatialite_osm_map, spatialite_osm_net, spatialite_osm_overpass: tools supporting OpenStreetMap datasets
    - XML-tools: spatialite_xml_load, spatialite_xml_collapse, spatialite_xml_print, spatialite_xml_validator, spatialite_xml2utf8: tools supporting XML files processing

  spatialite-tools are licensed under the GPL v3 (or any subsequent version) terms

base: core20

grade: devel
confinement: devmode # use 'strict' once you have the right plugs and slots

parts:
  libspatialite:
    plugin: autotools
    source-type: tar
    source: https://www.gaia-gis.it/gaia-sins/libspatialite-$SNAPCRAFT_PROJECT_VERSION.tar.gz
    override-build: |
      ./configure
      make -j"${SNAPCRAFT_PARALLEL_BUILD_COUNT}"
      make install-strip DESTDIR="${SNAPCRAFT_PART_INSTALL}"

    build-packages:
      - gcc
      - make
      - pkg-config
      - libproj-dev
      - libexpat1-dev
      - libreadosm-dev
      - libxml2-dev
      - libfreexl-dev
      - libgeos-dev
      - librttopo-dev
      - libminizip-dev
    stage-packages:
      - libexpat1
      - libreadosm1
      - libxml2
      - librttopo1
      - libminizip1
      - libfreexl1
      - libproj15

  spatialite-tools:
    plugin: autotools
    source-type: tar
    source: https://www.gaia-gis.it/gaia-sins/spatialite-tools-$SNAPCRAFT_PROJECT_VERSION.tar.gz
    override-pull: |
      snapcraftctl pull
      patch Makefile.am $SNAPCRAFT_PROJECT_DIR/spatialite-tools.patch
    override-build: |
      aclocal
      automake
      ./configure
      make -j"${SNAPCRAFT_PARALLEL_BUILD_COUNT}"
      make install-strip DESTDIR="${SNAPCRAFT_PART_INSTALL}"
    build-environment:
      - PKG_CONFIG_PATH: $SNAPCRAFT_STAGE/usr/local/lib/pkgconfig/
    after: [libspatialite]

  cleanup:
    after: [spatialite-tools]
    plugin: nil
    override-prime: |
      set -eux
      rm -rf \
        usr/local/include \
        usr/share/doc \
        usr/local/lib/pkgconfig

      # Remove sqlite loadable modules
      find . -type f,l -name mod_\* -exec rm \{} \;

      # Remove all static libraries
      find . -type f,l \( -name \*.a -or -name \*.la \) -exec rm \{} \;

apps:
  spatialite:
    command: usr/local/bin/spatialite
    environment:
      "LD_LIBRARY_PATH": "$SNAP/usr/local/lib"

  convert:
    command: usr/local/bin/spatialite_convert
    environment:
      "LD_LIBRARY_PATH": "$SNAP/usr/local/lib"

  dem:
    command: usr/local/bin/spatialite_dem
    environment:
      "LD_LIBRARY_PATH": "$SNAP/usr/local/lib"

  dxf:
    command: usr/local/bin/spatialite_dxf
    environment:
      "LD_LIBRARY_PATH": "$SNAP/usr/local/lib"

  gml:
    command: usr/local/bin/spatialite_gml
    environment:
      "LD_LIBRARY_PATH": "$SNAP/usr/local/lib"

  network:
    command: usr/local/bin/spatialite_network
    environment:
      "LD_LIBRARY_PATH": "$SNAP/usr/local/lib"

  osm-filter:
    command: usr/local/bin/spatialite_osm_filter
    environment:
      "LD_LIBRARY_PATH": "$SNAP/usr/local/lib"

  osm-map:
    command: usr/local/bin/spatialite_osm_map
    environment:
      "LD_LIBRARY_PATH": "$SNAP/usr/local/lib"

  osm-net:
    command: usr/local/bin/spatialite_osm_net
    environment:
      "LD_LIBRARY_PATH": "$SNAP/usr/local/lib"

  osm-overpass:
    command: usr/local/bin/spatialite_osm_overpass
    environment:
      "LD_LIBRARY_PATH": "$SNAP/usr/local/lib"

  osm-raw:
    command: usr/local/bin/spatialite_osm_raw
    environment:
      "LD_LIBRARY_PATH": "$SNAP/usr/local/lib"

  tool:
    command: usr/local/bin/spatialite_tool
    environment:
      "LD_LIBRARY_PATH": "$SNAP/usr/local/lib"

  xml-collapse:
    command: usr/local/bin/spatialite_xml_collapse
    environment:
      "LD_LIBRARY_PATH": "$SNAP/usr/local/lib"

  xml-load:
    command: usr/local/bin/spatialite_xml_load
    environment:
      "LD_LIBRARY_PATH": "$SNAP/usr/local/lib"

  xml-print:
    command: usr/local/bin/spatialite_xml_print
    environment:
      "LD_LIBRARY_PATH": "$SNAP/usr/local/lib"

  xml-validator:
    command: usr/local/bin/spatialite_xml_validator
    environment:
      "LD_LIBRARY_PATH": "$SNAP/usr/local/lib"

  xml2utf8:
    command: usr/local/bin/spatialite_xml2utf8
    environment:
      "LD_LIBRARY_PATH": "$SNAP/usr/local/lib"

  exif-loader:
    command: usr/local/bin/exif_loader
    environment:
      "LD_LIBRARY_PATH": "$SNAP/usr/local/lib"

  shp-doctor:
    command: usr/local/bin/shp_doctor
    environment:
      "LD_LIBRARY_PATH": "$SNAP/usr/local/lib"

  shp-sanitize:
    command: usr/local/bin/shp_sanitize
    environment:
      "LD_LIBRARY_PATH": "$SNAP/usr/local/lib"
