name: spatialite # you probably want to 'snapcraft register <name>'
version: '5.0.1'
summary: 'spatialite-tools is a collection of CLI tools supporting SpatiaLite'
description: |
  spatialite-tools is a collection of open source Command Line Interface (CLI) tools supporting SpatiaLite.

    - spatialite: a complete CLI front-end, more or less equivalent to the well known sqlite3 front-end, but fully supporting SpatiaLite
    - spatialite_tool: a tool supporting import/export of Shapefiles and DBF-files
    - shp_doctor: a diagnostic tool to check anomalous shapefiles
    - exif_loader: an import tool for EXIF or EXIF-GPS (JPEG) pictures
    - spatialite_network: a tool creating a VirtualNetwork (supporting shortest path / routing SQL queries)
    - spatialite_gml: a tool importing GML files
    - spatialite_convert: a tool converting DB-files from different versions of SpatiaLite
    - spatialite_dxf: an tool importing DXF files
    - OSM-tools: spatialite_osm_raw, spatialite_osm_filter, spatialite_osm_map, spatialite_osm_net, spatialite_osm_overpass: tools supporting OpenStreetMap datasets
    - XML-tools: spatialite_xml_load, spatialite_xml_collapse, spatialite_xml_print, spatialite_xml_validator, spatialite_xml2utf8: tools supporting XML files processing

  spatialite-tools are licensed under the GPL v3 (or any subsequent version) terms

base: core20

grade: devel
confinement: devmode # use 'strict' once you have the right plugs and slots

parts:
  libspatialite:
    plugin: autotools
    source-type: tar
    source: https://www.gaia-gis.it/gaia-sins/libspatialite-$SNAPCRAFT_PROJECT_VERSION.tar.gz
    build-packages:
      - gcc
      - make
      - pkg-config
      - libproj-dev
      - libexpat1-dev
      - libreadosm-dev
      - libxml2-dev
      - libfreexl-dev
      - libgeos-dev
      - librttopo-dev
      - libminizip-dev
    stage-packages:
      - libexpat1
      - libreadosm1
      - libxml2
      - librttopo1
      - libminizip1
      - libfreexl1
      - libproj15

  spatialite-tools:
    plugin: autotools
    source-type: tar
    source: https://www.gaia-gis.it/gaia-sins/spatialite-tools-$SNAPCRAFT_PROJECT_VERSION.tar.gz
    override-pull: |
      snapcraftctl pull
      patch Makefile.am $SNAPCRAFT_PROJECT_DIR/spatialite-tools.patch
    override-build: |
      aclocal && automake
      snapcraftctl build
    build-environment:
      - PKG_CONFIG_PATH: $SNAPCRAFT_STAGE/usr/local/lib/pkgconfig/
    after:
      - libspatialite
    build-packages:
      - gcc
      - make
      - libexpat1-dev
      - libreadosm-dev
      - libxml2-dev
    stage-packages:
      - libexpat1
      - libreadosm1
      - libxml2
      - libfreexl1
      - libproj15

apps:
  spatialite:
    command: usr/local/bin/spatialite
    environment:
      "LD_LIBRARY_PATH": "$SNAP/usr/local/lib"
